myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('', views.cobaTest, name='cobaTest'),
    path('delete/<id>', views.delete, name='delete'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    path('story10/', include('story10.urls'))
]

story10/urls.py
from django.urls import path
from . import views

app_name = 'story10'

urlpatterns = [
    path('', views.story10_index, name='story10_index')

]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.story7_index, name='story7_index'),

]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.story8_index, name='story8_index'),

]

story9/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'story9'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name="story9/story9_index.html", redirect_authenticated_user=True), name='story9_index'),
    path('login/', auth_views.LoginView.as_view(template_name="story9/login.html", redirect_authenticated_user=True), name="login"),
    path('profile/', views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name="story9/logout.html"), name="logout")

]

myapp/models.py
from django.db import models

# Create your models here.
class Coba(models.Model):
    status = models.CharField(max_length=300)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.status

story10/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

myapp/forms.py
from django import forms
from .models import Coba


class BuatStatus(forms.ModelForm):
    status = forms.CharField(widget=forms.Textarea, max_length=300)
    class Meta():
        model = Coba
        fields = ['status']
        

myapp/views.py
from django.shortcuts import render, redirect
from .forms import BuatStatus
from .models import Coba
from . import forms
from django.http import HttpResponseRedirect

# Create your views here.

def cobaTest(request):
    data = Coba.objects.all()
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = BuatStatus(request.POST or None)
        # check whether it's valid:
        if form.is_valid():
            form.save()
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/')
    
    # if a GET (or any other method) we'll create a blank form
    else:
        form = BuatStatus()

    return render(request, 'myapp/landing_page.html', {'form':form, 'data':data})

def delete(request, id):
    data = Coba.objects.get(id=id)
    data.delete()
    return HttpResponseRedirect('/')

story10/views.py
from django.shortcuts import render

# Create your views here.
def story10_index(request):
    return render(request, "story10/story10_index.html")

story7/views.py
from django.shortcuts import render

# Create your views here.
def story7_index(request):
    return render(request, "story7/story7_index.html")

story8/views.py
from django.shortcuts import render

# Create your views here.
def story8_index(request):
    return render(request, "story8/story8_index.html")

story9/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
def story9_index(request):
    return render(request, "story9/story9_index.html")

@login_required
def profile(request):
    return render(request, "story9/profile_story9.html")
    

templates/base_template.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

    <head>
        <title></title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
         integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
         
        <link rel="stylesheet" type="text/css" href= "{% static 'css/base_css.css' %}">
    </head>

    <body>
        <!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
         integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script> -->

        <script
         src="https://code.jquery.com/jquery-3.4.1.min.js"
         integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
         crossorigin="anonymous"></script>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
         integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

        <nav class="navbar navbar-expand-md navbar-fixed-top">
            <a class="navbar-brand" href="{% url 'myapp:cobaTest' %}">My Story</a>

            <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#main-navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="main-navigation">
                <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:cobaTest' %}">Story 6</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story7:story7_index' %}">Story 7</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story8:story8_index' %}">Story 8</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story9:story9_index' %}">Story 9</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story10:story10_index' %}">Story 10</a>
                </li>

                </ul>
            </div>
        </nav>

        {% block content %}

        {% endblock %}

    </body>

templates/myapp/landing_page.html
{% extends "base_template.html" %}
{% load static %}
{% block content %}
    <div>
        <h1 style="font-size: 30px; margin-left: 50px; margin-top: 30px;">Halo, apa kabar?</h1>
    </div>

    <div>
        <form method="POST">
            {% csrf_token %}
    
            {{ form.as_p }}
            <input type="submit" id="button_submit" style="margin-left: 50px;">
        </form>

        <div> 
            <ol>
                {% for i in data %}
                <li>
                    <a class="status_list">{{i.status}}</a> <br>
                    {{i.timestamp}} <br>
                    <a href="{% url 'myapp:delete' id=i.id %}"><button type="submit" style="margin-bottom: 15px">Delete</button></a>
                </li>
                {% endfor %}
            </ol>
        </div>
    </div>

{% endblock %}

templates/story10/story10_index.html
{% extends "base_template.html" %}
{% load static %}
{% block content %}
<div class="container">
    <h1 style="text-align: center;">My First Load Balancer</h1>
    
    <br>

    <p style="text-align: justify;">
        &emsp;&emsp;Load Balancing adalah teknik untuk mendistribusikan beban 
        traffic pada 2 atau lebih jalur koneksi secara seimbang, agar traffic dapat 
        berjalan optimal, memaksimalkan throughput, memperkecil response time dan 
        menghindari overload pada salah satu jalur koneksi. Jadi Load Balancer 
        adalah sesuatu yang melakukan Load Balancing. Mengapa Load Balancer ini
        <i>exist</i>? Pada dasarnya sesuatu itu diciptakan karena dibutuhkan. 
        Suatu website bisa mengalami <i>down</i> apabila jumlah pengunjung 
        melebihi kapasitas yang seharusnya. Disinilah peran Load Balancer 
        sangat dibutuhkan.
    </p>

    <p style="text-align: justify;">
        &emsp;&emsp;Ibaratnya, server adalah jalurnya, website adalah tujuan kita. 
        Banyak jalur untuk mencapai tempat yang kita tuju. Jika semua orang 
        menggunakan 1 jalur yang sama, maka akan terjadi <i>traffic jam</i>. 
        Oleh karena itu, semua orang yang berada di jalur yang sama itu 
        lebih baik melalui jalur yang berbeda-beda agar tidak terjadi 
        kemacetan yang sangat merugikan waktu kita. Karena komputer tidak 
        bisa membedakan mana jalur yang sepi dan mana jalur yang ramai, maka 
        Load Balancer lah yang memberikan arah. Load Balancer mendistribusikan 
        beban <i>traffic</i> secara merata sehingga dapat mengurangi kemacetan 
        dan respons yang diberikan oleh server pun menjadi cepat. Load Balancer 
        yang saya gunakan kali ini adalah <b>NGINX</b> (Engine-X) dengan framework Django.
    </p>
    <br>
    <p style="text-align: justify;">
        Berikut ini langkah-langkah simpel untuk menggunakan NGINX dengan Django:
    </p>

    <div>
        1. Pertama download terlebih dahulu NGINX-nya di 
        <a href="http://nginx.org/en/download.html">http://nginx.org/en/download.html</a>
        <br>
        <img src="{% static 'images/downloadnginx.png' %}" alt="" style="width: 100%; height: 100%; display: block; margin: 15px;">
        <br><br><br>
        
        2. Setelah itu simpan file nya di suatu tempat. Saya mendownloadnya yang versi di zip, 
        kemudian saya ekstrak, dan isinya seperti ini
        <br>
        <img src="{% static 'images/dir.png' %}" alt="" style="width: 100%; height: 100%; display: block; margin: 15px;">
        <br><br><br>

        3. Buka folder <b>conf</b>, buka file <b>nginx.conf</b> di text editor, saya mengubahnya kodenya menjadi seperti di bawah ini
        <br>
        <img src="{% static 'images/conf.png' %}" alt="" style="width: 100%; height: 100%; display: block; margin: 15px;">
        <br><br><br>

        4. Kalau sudah, buka cmd dengan directory yang di dalamnya Nginx yang sudah di ekstrak dan ketik <b>start nginx</b>
        <br>
        <img src="{% static 'images/startnginx.PNG' %}" alt="" style="width: 100%; height: 100%; display: block; margin: 15px;">
        <br><br><br>

        5. Buka cmd dengan directory project django dan kemudian ketik <b>python manage.py runserver 8000</b>, ulangi lagi tetapi 
        dengan port 9000, <b>python manage.py runserver 9000</b>. Ini kita artinya sudah memiliki 2 port yang menyala, 8000 dan 9000
        <br>
        <img src="{% static 'images/port8000.PNG' %}" alt="" style="width: 100%; height: 100%; display: block; margin: 15px;">
        <br><br><br>

        6. Setelah 5 langkah di atas sudah selesai, buka tab baru di browser yang digunakan, kemudian ketik <b>server_name</b> sesuai 
        dengan yang ada di <b>nginx.conf</b>. Disini saya membuat server_name-nya <b>localhost</b>.
        <br>
        <img src="{% static 'images/openserver.png' %}" alt="" style="width: 100%; height: 100%; display: block; margin: 15px;">
        <br><br><br>

        Jika di refresh, di masing-masing cmd yang melakukan runserver akan terlihat server mana yang sedang di akses, jika 
        port 8000 yang di akses maka akan muncul sesuatu di cmd-nya, begitu juga dengan port 9000. Selamat mencoba.
        <br>
        <br>
        Selesai! Selamat sudah menyelesaikan tutorial ini!
        <div style="height: 100px;">

        </div>

    </div>
</div>
{% endblock %}

templates/story7/story7_index.html
{% extends "base_template.html" %}
{% load static %}
{% block content %}

<div>
    <button class="btn btn-primary" id="ubah" style="margin-left: 15px; margin-top: 10px;">Ubah Tema</button>
</div>

<div style="margin-top: 30px;"></div>
    <div class="menu">
        <p class="mystyle">Aktivitas</p>
        <ul class="content">
        <li>Kuliah</li>
        <li>Nugas</li>
        <li>Sakit</li>
        </ul>
    </div>
    <div class="menu ">
        <p class="mystyle">Organisasi/Kepanitiaan</p>
        <ul class="content hidden">
        <li>KMBUI</li>
        </ul>
    </div>
    <div class="menu">
        <p class="mystyle">Prestasi</p>
        <ul class="content hidden">
        <li>Finalis OSN Fisika (2013)</li>
        </ul>
    </div>
</div>

<script type="text/javascript" src="{% static 'main.js' %}"></script>
{% endblock %}

templates/story8/story8_index.html
{% extends "base_template.html" %}
{% load static %}
{% block content %}

<div class="d-flex justify-content-center align-items-center container">
    <form id="input-form" class="container" style="margin-bottom: 20px;">
        <div class="row d-flex justify-content-center align-items-center">
            <div class="col-10">
                <input class="form-control form-control-sm mr-3 w-100 text-align-center" id="searchbox" type="text"
                    placeholder="Search" aria-label="Search" autocomplete="off">
            </div>
            <div class="col-2">
                <input type="submit" id="cari" class="btn btn-primary mx-auto" value="Search" />
            </div>
        </div>
    </form>
</div>

<div class="container" id="tabel">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Image</th>
                <th scope="col">Title</th>
                <th scope="col">Author</th>
                <th scope="col">Link</th>
            </tr>
        </thead>
        <tbody id="cont">
        </tbody>
    </table>
</div>



<script type="text/javascript" src="{% static 'story8.js' %}"></script>

{% endblock %}

templates/story9/login.html
{% extends "base_template.html" %}

{% block content %}

<div style="margin: 20px;">
    {% if form.errors %}

    <p>Your username and password didn't match. Please try again.</p>

    {% endif %}

    {% if next %}

        {% if user.is_authenticated %}

        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>

        {% else %}

        <p>Please login to see this page.</p>

        {% endif %}
    {% endif %}

    <form method="post" action="{% url 'story9:login' %}">
    {% csrf_token %}
    <table>
    <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
    </tr>
    <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
    </tr>
    </table>

    <input type="submit" value="Login" class="btn btn-primary">
    <input type="hidden" name="next" value="{{ next }}">
    </form>
</div>

{% endblock %}

templates/story9/logout.html
{% extends "base_template.html" %}
{% load static %}
{% block content %}
<div style="margin: 20px;">
    <h1>{{ title }} successfully.</h1>
    <a href="{% url 'story9:story9_index' %}"><button class="btn btn-primary">Home</button></a>
</div>
{% endblock %}

templates/story9/profile_story9.html
{% extends "base_template.html" %}
{% load static %}
{% block content %}
<div style="margin: 20px">
    <h1>Welcome, {{ user.username }} ({{ user.first_name }} {{ user.last_name }}).</h1>
    <a href="{% url 'story9:logout' %}"><button class="btn btn-primary">Logout</button></a>
</div>

{% endblock %}

templates/story9/story9_index.html
{% extends "base_template.html" %}
{% load static %}
{% block content %}
<div style="margin: 20px"> 
    <h1>Hello, please login :)</h1>
    <a href="{% url 'story9:login' %}"><button class="btn btn-primary">Login</button></a>
</div>
{% endblock %}